accounts/urls.py
# accounts/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views
from django_registration.backends.one_step.views import RegistrationView

app_name = 'accounts'

urlpatterns = [

    url(r'^accounts/register/', RegistrationView.as_view(success_url='/time'), name='django_registration_register'),
    
    url(r'^accounts/', include('django_registration.backends.one_step.urls')),
    
    #url(r'^accounts/', include('django.contrib.auth.urls',namespace='')),
]

time_app/urls.py
from django.conf.urls import include, url
from django.urls import path 
from django.contrib import admin
from time_app import views
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth.views import auth_logout, auth_login
from django.contrib.auth import views as auth_views 
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'time_app'

urlpatterns = [

    url(r'^$', views.list, name='list'),
    url(r'^edit/(?P<pk>\d+)$', views.edit, name='edit'),
    url(r'^new$', views.create, name='new'),
    url(r'^delete/(?P<pk>\d+)$', views.delete, name='delete'),
    url(r'^set_timezone$', views.set_timezone, name='set_timezone'),
    
    url(r'base_layout',views.base_layout,name='base_layout'),
    url(r'getdata',views.getdata,name='getdata'),
    url('', include('pwa.urls')),
    
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('api-token-auth/', obtain_auth_token, name='api_token_auth'), 
    
]

time_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from rest_framework import routers, serializers, viewsets
from time_app import views

app_name = 'time'

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'time', views.TimeViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^api/', include(router.urls)),

    url('', include('time_app.urls',  namespace='time')),
    
    url('', include('accounts.urls',  namespace='accounts')),
    
    url(r'^accounts/', include('django.contrib.auth.urls',namespace='')),
    
    url(r'^tz_detect/', include('tz_detect.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

time_app/models.py
from django.db import models
#from django.contrib.auth.models import User

#from django_currentuser.middleware import (
#    get_current_user, get_current_authenticated_user)
#from django_currentuser.db.models import CurrentUserField

#https://docs.djangoproject.com/en/2.1/topics/auth/customizing/
from django.conf import settings
#from django.db.models.signals import post_save
from datetime import timedelta
#from datetime import datetime 
from django.utils import timezone

def now_round_min(): 
    #print(timezone.now().replace(second=0, microsecond=0))
    return timezone.localtime(timezone.now()).replace(second=0, microsecond=0) 

def now_round_hour_min():
    return timezone.localtime(timezone.now()).replace(second=0,minute=0, microsecond=0)+timedelta(hours=2)
    #return now().replace(second=0,minute=0, microsecond=0)+timedelta(hours=2)
    
# Create your models here.
class time_entry(models.Model):

    #print("timezone.now",timezone.now)
    
    date = models.DateField(default=timezone.now)
    start_time =  models.TimeField(default=now_round_min)
    end_time = models.TimeField(default=now_round_hour_min)
    name = models.CharField(max_length=200)
    #https://wsvincent.com/django-referencing-the-user-model/
    #created_by = CurrentUserField()
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hours_break = models.FloatField(default=0)
    hours_worked = models.FloatField(default=0)
    
    def __str__(self):
        return self.name
    
    @property
    def duration(self):
        end = timedelta(hours=self.end_time.hour, minutes=self.end_time.minute, seconds=self.end_time.second)
        start = timedelta(hours=self.start_time.hour, minutes=self.start_time.minute, seconds=self.start_time.second)
        
        return ((end - start).seconds - self.hours_break*3600) / 3600
    
    def save(self,*args,**kwargs):
        self.hours_worked = self.duration
        super().save(*args, **kwargs)
        
class time_summary(time_entry):
    class Meta:
        proxy = True
        verbose_name = "Time Summary"
        verbose_name_plural = "Times Summary"

time_app/forms.py
from django.forms import ModelForm
from django import forms
from time_app.models import time_entry
#from django.contrib.admin import widgets  
from django.forms.widgets import NumberInput

# https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker-in-django

class DeltaForm(forms.Form):
    delta_days = forms.IntegerField(label='Days',min_value=0)

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class PostsForm(ModelForm):
    class Meta:
        model = time_entry
        fields = ['name', 'date','start_time', 'end_time', 'hours_break']
        widgets = {
            'date': DateInput(),
            'start_time': TimeInput(),
            'end_time': TimeInput(),
            'hours_break': NumberInput()
        }

time_app/views.py
from time_app.models import time_entry
from django.shortcuts import render, redirect, get_object_or_404
from time_app.forms import PostsForm
from .serializers import UserSerializer
        
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse
from django.db.models import Sum, Count
from django.utils import timezone
from datetime import timedelta
from .forms import DeltaForm
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
import pytz
from rest_framework import viewsets, permissions
from .permissions import IsOwnerOrReadOnly
from django.contrib.auth.models import User, Group
from .permissions import IsAccountAdmin
from .serializers import TimeSerializer

@login_required(login_url='/time/accounts/login/')
def list(request, template_name='list.html'):
    
    now = timezone.now()
    delta_days = 1;
    
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DeltaForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            delta_days = form.cleaned_data['delta_days']

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DeltaForm()
    
    startdate = now - timedelta(days=delta_days)
    enddate = now + timedelta(days=1)
    
    te = time_entry.objects.filter(user_id=request.user, date__range=[startdate, enddate])
    #data = {}
    #data['object_list'] = posts
    
    #.values > group by
    sub_totals = time_entry.objects.values('name').filter(user_id=request.user, date__range=[startdate, enddate]).annotate(Sum('hours_worked'))
    
    total = 0
    for time in te:
        total += time.duration       
    
    jsondata = serializers.serialize('json',te)
    
    context={
        'results':te,
        'sub_totals': sub_totals,
        'jsondata':jsondata,
        'total':total,
    }
    
    #print(sub_totals)
    
    #return render(request, template_name, data, context)
    return render(request, template_name, context, {'form': form})

@login_required(login_url='/time/accounts/login/')
def edit(request, pk, template_name='edit.html'):
    post = get_object_or_404(time_entry, pk=pk, user_id=request.user)
    form = PostsForm(request.POST or None, instance=post)
    #print("get_timezone", request.session['django_timezone'])
    if form.is_valid():
        form.save()
        return redirect('time_app:list')
    return render(request, template_name, {'form': form})

@login_required(login_url='/time/accounts/login/')
def delete(request, pk, template_name='delete.html'):
    post = get_object_or_404(time_entry, pk=pk, user_id=request.user)
    if request.method=='POST':
        post.delete()
        return redirect('time_app:list')
    return render(request, template_name, {'object': post})

@login_required(login_url='/time/accounts/login/')
def create(request, template_name='edit.html'):
    form = PostsForm(request.POST or None)
    
    if 'django_timezone' not in request.session:
        print("views.django_timezone not set")  
    else :
        print("views.get_timezone", request.session['django_timezone'])    
    
    if form.is_valid():
        form.instance.user_id = request.user
        form.save()
        return redirect('time_app:list')
    return render(request, template_name, {'form': form})

@login_required(login_url='/time/accounts/login/')
def getdata(request):
    results=time_entry.objects.filter(user_id=request.user)
    jsondata = serializers.serialize('json',results)
    return HttpResponse(jsondata)

@login_required(login_url='/time/accounts/login/')
def base_layout(request):
    template='base.html'
    return render(request,template)

@login_required(login_url='/time/accounts/login/')
def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        print("set_timezone", request.session['django_timezone'])
        return redirect('/time')
    else:
        return render(request, 'set_tz.html', {'timezones': pytz.common_timezones})
    
class BaseViewSet (viewsets.ModelViewSet ):
    permission_classes = [permissions.IsAuthenticated, IsOwnerOrReadOnly]
    
    def get_queryset(self):
        qs = self.queryset.filter(user_id=self.request.user)
        return qs
    def perform_create(self, serializer):
        serializer.save(user_id = self.request.user)
        
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [IsAccountAdmin]

class TimeViewSet(BaseViewSet):
    queryset = time_entry.objects.all().order_by('name')
    serializer_class = TimeSerializer

time_app/templates/base.html
<html>
{% load pwa %}
{% load static %}

{% load tz %}
{% localtime on %}

<head>
	{% progressive_web_app_meta %}
	<title>Time</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
	
	<link rel="stylesheet" type="text/css" href="/time/static/css-frames-style.css" />
	
	<script>
		this.online = window.navigator.onLine;
        window.addEventListener('online', () => this.online = true);
        window.addEventListener('offline', () => this.online = false);
  	</script>
	
</head>
<body>
	<div id="header-wrapper" class="wrapper">
				
		<div id="sidebar">
		<ul>
		  <li><a class="active" href="/time">Home</a></li>
		  <li><a href="#contact">Contact</a></li>
		  <li><a href="#about">About</a></li>
		</ul>
		</div>
		
		<div id="footerbar" class="footer bg-dark">
		<p>&copy Time Manager 2018</p>
		<ul>
		  <li><a href="#home">Privacy policy</a></li>
		  <li><a href="#news">Contact us</a></li>
		  <li><a href="/time/set_timezone">Timezone</a></li>
		</ul>
		</div>
		
		<div style="padding:20px;margin-top:30px;height:1500px;" class="container">
			<br><br><br>
			{% block content %}

			{% endblock %}
			<div id="offlinedata" hidden="[online]">
				<!-- the news will get displayed here from indexedDB in offline mode -->
			</div>
		<script type="text/javascript" src="{% static 'js/idb.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/idbop.js' %}"></script>
		</div>
		
		<div id="footer-wrapper" class="footer bg-dark">
			<p>&copy Time Manager 2018</p>
			<a class="alink" href="/privacy">Privacy policy</a>&nbsp
			<a class="alink" href="/contact">Contact us</a>
			<a class="alink" href="/set_timezone">Timezone</a>
		</div>
	</div>

{% endlocaltime %}
</body>
</html>

time_app/templates/delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input class="btn btn-primary" type="submit" value="Submit" />
  </form>
</div>

{% endblock %}

time_app/templates/edit.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <h1>Time Entry</h1>
  <form  method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Submit" />
  </form>
</div>

{% endblock %}

time_app/templates/email.html
{% block content %}
{% load static %}

<p><p><b>Summary</b></p>
<table cellpadding="0" cellspacing="0" width="640" align="left" border="1">
<tr>
	<th>name</th>
	<th>time (hrs)</th>
</tr>
	
{% for item in sub_totals %}
	<tr>
		<th>{{ item.name }}</th>
		<th>{{ item.hours_worked__sum|floatformat:2 }}</th>
	</tr>
{% endfor %}

<tr>
	<th>Total</th>
	<th>{{total|floatformat:2}}</th>
</tr>

</table>


<p><p><b>Time Sheet</b></p>
<table cellpadding="0" cellspacing="0" width="640" align="left" border="1">
{% for post in results %}

<tr>
<th><a href="{% url "time_app:edit" post.id %}">{{ post.id }}</a></th>
<th>{{ post.date }}</th>
<th>{{ post.name }}</th>		
<th>Start: {{ post.start_time }}</th>
<th>{{ post.end_time }}</th> 
<th>{{ post.duration|floatformat:2 }}</th> 
<th><a href="{% url "time_app:delete" post.id %}">Delete</a></th>
</tr>
      
{% endfor %}

</table>

{% endblock %}

time_app/templates/list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load mathfilters %}
{% load widget_tweaks %}

{% if user.is_authenticated %}
<p>Welcome, {{ user.username }}. </p>
<p><a href="/time/accounts/logout">Logout</a></p>

<div class="container">
<h1>Time Log</h1>

<form method="post">
    {% csrf_token %}
    <div class="well">
      <h4 style="margin-top: 0">Filter (days)</h4>
      <input id="delta_days" type="text" name="delta_days" value="{{ delta_days }}">
      
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>


<table style="width:100%">
{% for post in results %}

<tr>
<th><a href="{% url "time_app:edit" post.id %}">{{ post.id }}</a></th>
<th>{{ post.date|date:'l d N, Y' }}</th>
<th>{{ post.name }}</th>		
<th>Start: {{ post.start_time }}</th>
<th>{{ post.end_time }}</th> 
<th>{{ post.duration|floatformat:2 }}</th> 
<th><a href="{% url "time_app:delete" post.id %}">Delete</a></th>
</tr>
      
{% endfor %}

</table>
</ul>

<a href="{% url "time_app:new" %}">New time entry</a>

<p><p><b>Project Summary</b></p>
<table style="width:100%">
<tr>
	<th>name</th>
	<th>time (hrs)</th>
</tr>
	
{% for item in sub_totals %}
	<tr>
		<th>{{ item.name }}</th>
		<th>{{ item.hours_worked__sum|floatformat:2 }}</th>
	</tr>
{% endfor %}

<tr>
	<th>Total</th>
	<th>{{total|floatformat:2}}</th>
</tr>

</table>

</div>



{% else %}
<p>Welcome, new user. Please <a href="accounts/login">log in</a>.</p>

<p><a href="accounts/register">Register</a></p>

{% endif %}
	
{% endblock %}

time_app/templates/set_tz.html
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<form action="{% url 'time_app:set_timezone' %}" method="POST">
    {% csrf_token %}
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for tz in timezones %}
        <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set">
</form>